stages:
  - build
  - test

variables:
  SBT_OPTS: "-Xms512M -Xmx2G"

image: sbtscala/scala-sbt:eclipse-temurin-17.0.10_7_1.10.1_3.3.3

build:
  stage: build
  script:
    - sbt clean compile

test:
  stage: test
  script:
    - sbt test