slick.dbs.default.profile = "slick.jdbc.PostgresProfile$"
slick.dbs.default.db.driver = "org.postgresql.Driver"
slick.dbs.default.db.url = "jdbc:postgresql://localhost:5432/AraMjb"
slick.dbs.default.db.user = ${DB_USER}
slick.dbs.default.db.password = ${DB_PASSWORD}

#Bind
play.modules.enabled += "Module"

play.evolutions.db.default.autoApply=true
play.evolutions.db.default.autoApplyDowns=true
#: CSRF (Cross-Site Request Forgery) protection.
play.filters.disabled += "play.filters.csrf.CSRFFilter"