package repositories.write

import com.google.inject.{Inject, Singleton}
import domain.models.User
import infrastructure.persistence.tables.UsersTable
import mappers.UserMapper
import play.api.db.slick.DatabaseConfigProvider
import slick.jdbc.JdbcProfile


import java.util.UUID
import scala.concurrent.{ExecutionContext, Future}

@Singleton
class SlickUserWriteRepository @Inject()(databaseConfigProvider: DatabaseConfigProvider,
                                         mapper:UserMapper)(implicit ec: ExecutionContext) extends UserWriteRepository
{
  // Load the JDBC profile (PostgreSQL)
  private val dbConfig = databaseConfigProvider.get[JdbcProfile]

  // Essential import for Slick DSL operators
  import dbConfig.profile.api._

  // Access the underlying database instance
  private val db = dbConfig.db

  // Use the pre-defined TableQuery from the companion object
  private val q = TableQuery[UsersTable]


//  Inserts a new user into the database.
//   * * Uses Slick's 'returning' syntax to handle auto-generated IDs or to
//   * ensure the ID generated by the DB is captured back into the domain object.
  override def createUser(user: User): Future[User] = {
    val row = mapper.toRow(user)

    // Mapping the newly created ID back into the original row object
    val insertQuery = q returning q.map(_.id) into ((item, id) => item.copy(id = id))

    db.run(insertQuery += row).map(mapper.fromRow)

  }

  /**
   * Updates an existing user record.
   * Matches the record by UUID and replaces the entire row with the new data.
   * * @return Future[Int] representing the number of rows affected (should be 1)
   */
  override def updateUser(user: User): Future[Int] = {
    val row = mapper.toRow(user)

    // Filter by ID to ensure we only update the specific user
    db.run(q.filter(_.id === user.id).update(row))
  }

  /**
   * Removes a user record from the system.
   * * @param id The UUID of the user to delete
   * @return Future[Int] representing the number of rows deleted
   */
  override def deleteUser(id: UUID): Future[Int] = {
    db.run(q.filter(_.id === id).delete)
  }
}
