package repositories

import com.google.inject.{Inject, Singleton}
import domain.models.{User, UsersRole}
import infrastructure.persistence.models.UsersRow
import infrastructure.persistence.tables.UsersTable
import play.api.db.slick.DatabaseConfigProvider
import slick.jdbc.JdbcProfile

import java.util.UUID
import scala.concurrent.{ExecutionContext, Future}
import scala.util.Try

@Singleton
class SlickUserRepository @Inject()(databaseConfigProvider: DatabaseConfigProvider,
                                    mapper:UsersRow)(implicit ec: ExecutionContext) extends UserRepository
{
  // Load the JDBC profile (PostgreSQL)
  private val dbConfig = databaseConfigProvider.get[JdbcProfile]
  import dbConfig.profile.api._
  private val db = dbConfig.db
  private val q = TableQuery[UsersTable]


//  Inserts a new user into the database.
//   * * Uses Slick's 'returning' syntax to handle auto-generated IDs or to
//   * ensure the ID generated by the DB is captured back into the domain object.
  override def createUser(user: User): Future[Try[User]] = {
    val row = mapper.toRow(user)

    // Mapping the newly created ID back into the original row object
    val insertQuery = q returning q.map(_.id) into ((item, id) => item.copy(id = id))
    val query = insertQuery += row
    db.run(query.asTry).map(_.map(mapper.fromRow))

  }

  /**
   * Updates an existing user record.
   * Matches the record by UUID and replaces the entire row with the new data.
   */
  override def updateUser(user: User): Future[Try[Int]] = {
    val row = mapper.toRow(user)

    // Filter by ID to ensure we only update the specific user
    val filter = q.filter(_.id === user.id).update(row)
    db.run(filter.asTry)
  }

  /**
   * Removes a user record from the system.
   * * @param id The UUID of the user to delete
   */
  override def deleteUser(id: UUID): Future[Try[Int]] = {
    val userId = q.filter(_.id === id).delete
    db.run(userId.asTry)
  }

  //  Fetches a single user by their unique identifier.
  //   Maps Future[Option[UsersRow]] to Future[Option[User]]
  override def findUserbyId(id: UUID): Future[Option[User]] ={
    db.run(q.filter(_.id === id).result.headOption).map(_.map(mapper.fromRow))

  }

  //  Retrieves a user by their email address.
  override def findUserByEmail(email:String): Future[Option[User]] = {
    db.run(q.filter(_.email === email).result.headOption).map(_.map(mapper.fromRow))
  }

  //  Finds all users associated with a specific role
  override def findUserByRole(role: UsersRole): Future[Seq[User]] = {
    db.run(q.filter(_.role === role).result).map(_.map(mapper.fromRow))
  }

  /**
   * Provides a paginated list of users sorted alphabetically by name.
   * @param offset Number of records to skip
   * @param limit Maximum number of records to return
   */
  override def listAllUsers(offset: Int, limit: Int): Future[Seq[User]] = {
    db.run(
      q.sortBy(_.name.asc) // Standardize sorting for consistent UI/UX
        .drop(offset)      // Skip previous records (Pagination)
        .take(limit)      // Limit result set size (Performance)
        .result
    ).map(_.map(mapper.fromRow))
  }
}
