stages:
  - build
  - test

variables:
  SBT_OPTS: "-Xms512M -Xmx2G"

image: sbtscala/scala-sbt:latest

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - ~/.ivy2/cache
    - ~/.sbt
    - target/

build:
  stage: build
  script:
    - sbt clean compile

test:
  stage: test
  script:
    - sbt test
